### ISSUE TITLE
Why most pipelines show "Unknow" as user who triggered?

### ISSUE THREAD

**Issue by hbsis-fernandomedeiros** [karmats/gocd-monitor#12]
I have a few deploy pipelines, that isn't started by any changes... Instead, they're manually triggered.

https://s14.postimg.org/rabkajk35/Triggered_Go_CD.png

GoCD shows it just fine, by gocd-monitor, don't.

https://s11.postimg.org/3ouu1ww03/Triggered_Go_CDMonitor.png

What am I doing wrong?

Thanks! :)

**Comment by karmats** [comment]
A name will only show up if the pipeline was triggered by changes. I will investigate if it's possible to retrieve the name of the person that triggers it if it is a manual build. Thanks for pointing this out :)
