### ISSUE TITLE
Suggestion: Support multiple teams

### ISSUE THREAD

**Issue by flosell** [karmats/gocd-monitor#53]
I'm currently working in a set-up where multiple teams are using the same GoCD instance but are responsible for different parts of the system and therefore interested in different pipelines. Some pipelines are of interest for multiple teams while other pipelines are only interesting for a single team. 

At the moment, we deploy one instance of gocd-monitor for each team. This works OK but is a big overhead, esp. as the number of teams grow. Therefore, it would be nice if gocd-monitor would support multiple teams out of the box. 

Two approaches I can think of: 

* Store settings for multiple teams and give them a way of selecting their set of settings. This is more or less straightforward to implement since it extends the current concept quite nicely. However, it's still shared state: ones change influences others, teams need to know who is using which settings-set, ...; Also, the state needs to be persistent, making immutable infrastructure a bit harder. 
* Define settings in URL: This seems to be more complex since the current code-base isn't really intended to do this so probably needs some refactoring. Also, if this is added to the existing, persistent settings mechanism it becomes quite hard to reason about (both for developers and users): What happens if I have one setting in the URL but then change it in the UI? What if some settings are defined in the URL and others aren't? What if something is defined in both?

**Comment by karmats** [comment]
Fixed in #54
