### ISSUE TITLE
Doesn't work without "operate" permissions.

### ISSUE THREAD

**Issue by ccbrown** [karmats/gocd-monitor#6]
When the configured user only has "view" permissions, but not "operate", all of the pipelines appear paused. The monitor determines whether or not the pipeline is paused by looking at the "can_run" key from the pipelines API, but this key is never `true` if the user doesn't have operate permissions. So as a result, all of the pipelines are displayed as paused.

As a matter of security, it would be preferable to function with as few permissions as possible.

The authoritative way to determine if a pipeline is paused would be via the dashboard or pipeline status API.

Great monitor btw. Thanks!

**Comment by karmats** [comment]
Thanks @ccbrown Will look into this
